### ISSUE TITLE
Problems using the plugin

### ISSUE THREAD

**Issue by schjonhaug** [zwerch/homebridge-webos2#2]
Hi,

I've successfully added the plugin, but when I try to use it, I run into problems. When homebridge is launching the plugin my TV displays this:

![img_3306](https://cloud.githubusercontent.com/assets/84225/18094183/dd0abcfa-6ed2-11e6-9ab0-f04167d8d1e7.jpg)

It says "Request to connect: LG Remote App. If you accept this connection, LG Remote App may access and save information about your TV". I click on yes, but homebridge fails with this (newest log message on top):

```
Aug 30 14:54:40 raspberrypi systemd[1]: Unit homebridge.service entered failed state.
Aug 30 14:54:40 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Aug 30 14:54:40 raspberrypi homebridge[5327]: at Error (native)
Aug 30 14:54:40 raspberrypi homebridge[5327]: Error: EACCES: permission denied, open './lgtv-10.0.1.32'
Aug 30 14:54:40 raspberrypi homebridge[5327]: ^
Aug 30 14:54:40 raspberrypi homebridge[5327]: throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
Aug 30 14:54:40 raspberrypi homebridge[5327]: fs.js:101  
```

**Comment by schjonhaug** [comment]
Also, when the TV is off, the plugin makes homebridge fail (newest log message on top):

```
Aug 30 15:07:13 raspberrypi systemd[1]: Unit homebridge.service entered failed state.
Aug 30 15:07:13 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Aug 30 15:07:13 raspberrypi homebridge[5491]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
Aug 30 15:07:13 raspberrypi homebridge[5491]: at exports._exceptionWithHostPort (util.js:1049:20)
Aug 30 15:07:13 raspberrypi homebridge[5491]: at Object.exports._errnoException (util.js:1026:11)
Aug 30 15:07:13 raspberrypi homebridge[5491]: Error: connect EHOSTUNREACH 10.0.1.32:3000
Aug 30 15:07:13 raspberrypi homebridge[5491]: ^
Aug 30 15:07:13 raspberrypi homebridge[5491]: throw er; // Unhandled 'error' event
Aug 30 15:07:13 raspberrypi homebridge[5491]: events.js:160
Aug 30 15:07:12 raspberrypi homebridge[5491]: [2016-08-30 15:07:12] Homebridge is running on port 51826.
```

**Comment by toshibochan** [comment]
Same for me to. If tv is off homebridge crash. If tv is on can turn tv off but if off homebridge crash.

**Comment by toshibochan** [comment]
My webos is 1.4.0-2515(Afro-Ashley)
I don't know why say Afro-Ashley!

**Comment by zwerch** [comment]
I can confirm this issue, but I'm currently unable to help.

Please consider fixing it and creating a Pull-Request, I would be happy to accept it!
